grpc:
  server:
    port: 3005
  client:
    im:
      address: 'static://127.0.0.1:3004'
      negotiation-type: plaintext
spring:
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: password
  datasource:
    url: jdbc:mysql://localhost:3306/violet?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  elasticsearch:
    uris: localhost:9200
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    region: cn-beijing
    bucket-name: violet-feed
    access-key-id: 111
    access-key-secret: 111
minimax:
  api-key: 111