grpc:
  server:
    port: 3005
  client:
    action:
      address: 'static://127.0.0.1:3003'
      negotiation-type: plaintext
    im:
      address: 'static://127.0.0.1:3004'
      negotiation-type: plaintext
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/violet?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: aigc_consumer
      auto-offset-reset: earliest
  redis:
    host: localhost
    port: 6666
    password:
nebula:
  address: localhost
  port: 9669
  username: root
  password: 123456
milvus:
  uri: http://localhost:19530
  token: root:Milvus
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    region: cn-beijing
    bucket-name: violet-feed
    access-key-id: xxx
    access-key-secret: xxx
  dashscope:
    api-key: xxx
minimax:
  api-key: xxx