grpc:
  server:
    port: 3005
  client:
    im:
      address: 'static://127.0.0.1:3004'
      negotiation-type: plaintext
spring:
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: xxx
  datasource:
    url: jdbc:mysql://localhost:3306/violet?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xxx
  elasticsearch:
    uris: localhost:9200
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: aigc_consumer
      auto-offset-reset: earliest
nebula:
  address: localhost
  port: 9669
  username: nebula
  password: xxx
milvus:
  uri: http://localhost:19530
  token: root:xxx
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    region: cn-beijing
    bucket-name: violet-feed
    access-key-id: xxx
    access-key-secret: xxx
  dashscope:
    api-key: xxx
minimax:
  api-key: xxx